---
Name: approutes
After:
 - '#rootroutes'
 - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'user//$Action': 'App\Controllers\RandomUserPageController'
    'users//$Action': 'App\Controllers\RandomUsersPageController'
